project:
  type: sdca-theme

website:
  title: "SDCA Epi Stats"
  site-url: "https://steno-aarhus.github.io/epi-stats/"
  repo-url: "https://github.com/steno-aarhus/epi-stats"
  navbar:
    pinned: true
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
      - icon: twitter
        href: "https://twitter.com/StenoAarhusRes"
      - icon: three-dots-vertical
        menu:
          - text: Official site
            href: "https://www.stenoaarhus.dk/research"
          - text: Common Docs
            href: "https://steno-aarhus.github.io/research"
          - text: Epi Stats
            href: "https://steno-aarhus.github.io/epi-stats"
          - text: Register Space
            href: "https://steno-aarhus.github.io/register-space"

format: sdca-theme-html

editor_options:
  markdown:
    wrap: 72
    canonical: true
